import{a as m,S as f,i as h}from"./assets/vendor-BjmtRwYh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const p="45077821-aa67b100696f1310c7d1f60f1",g="https://pixabay.com/api/";async function d(t,r=1,a=15){const s=`${g}?key=${p}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{return(await m.get(s)).data}catch(e){throw console.error("Fetching images failed:",e),e}}let u;function y(t){const r=document.querySelector(".gallery"),a=t.map(s=>S(s)).join("");r.insertAdjacentHTML("beforeend",a),u?u.refresh():u=new f(".gallery a")}function S({webformatURL:t,largeImageURL:r,tags:a,likes:s,views:e,comments:o,downloads:l}){return`
    <div class="gallery-item">
      <a href="${r}">
        <img src="${t}" alt="${a}" loading="lazy" width="360" height="152" />
      </a>
      <div class="info">
        <ul class="descr-list">
          <li><h2 class="title">Likes:</h2><p class="text">${s}</p></li>
          <li><h2 class="title">Views:</h2><p class="text">${e}</p></li>
          <li><h2 class="title">Comments:</h2><p class="text">${o}</p></li>
          <li><h2 class="title">Downloads:</h2><p class="text">${l}</p></li>
        </ul>
      </div>
    </div>
  `}function q(){const t=document.querySelector(".gallery");t.innerHTML=""}function i(t){h.error({title:"Error",message:t,position:"bottomRight"})}let n=1,c="";document.querySelector("#search-form").addEventListener("submit",async t=>{if(t.preventDefault(),c=t.currentTarget.elements.searchQuery.value.trim(),c===""){i("Please enter a search query");return}n=1,q(),document.querySelector(".loader-text").style.display="block",document.querySelector(".load-more").style.display="none";try{const r=await d(c,n);r.hits.length===0?i("Sorry, there are no images matching your search query. Please, try again!"):(y(r.hits),r.totalHits>15&&(document.querySelector(".load-more").style.display="block"))}catch{i("Something went wrong. Please try again later.")}finally{document.querySelector(".loader-text").style.display="none"}});document.querySelector(".load-more").addEventListener("click",async()=>{n+=1,document.querySelector(".loader-text").style.display="block";try{const t=await d(c,n);y(t.hits),n*15>=t.totalHits&&(document.querySelector(".load-more").style.display="none",i("We're sorry, but you've reached the end of search results."))}catch{i("Something went wrong. Please try again later.")}finally{document.querySelector(".loader-text").style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
